DROP SCHEMA IF EXISTS sc6_events  CASCADE;
CREATE SCHEMA sc6_events;
SET search_path TO sc6_events, public;

CREATE TABLE events (
    event_id   integer PRIMARY KEY,
    event_name text    NOT NULL,
    available_seats integer NOT NULL CHECK (available_seats >= 0)   
);

CREATE TABLE bookings (
    booking_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    event_id   integer NOT NULL REFERENCES events(event_id),
    student_number text    NOT NULL,
    seats   integer NOT NULL CHECK (seats > 0),
    status  text    NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

INSERT INTO events (event_id, event_name, available_seats)
VALUES (1, 'Orientation Day', 100),
       (2, 'Career Fair', 10),
       (3, 'Graduation Gala', 0);

SELECT * FROM events ORDER BY event_id;


DO $$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT event_name, available_seats FROM sc6_events.events ORDER BY event_id LOOP
        IF r.available_seats = 0 THEN
            RAISE NOTICE 'Event "%" is full', r.event_name;
        ELSIF r.available_seats <= 10 THEN
            RAISE NOTICE 'Event "%" is nearly full: % seats left', r.event_name, r.available_seats;
        ELSE
            RAISE NOTICE 'Event "%" has plenty of seats: %', r.event_name, r.available_seats;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


DO $$
DECLARE
    v_n integer := 1;
BEGIN
    WHILE v_n <= 3 LOOP
        RAISE NOTICE 'Booking reminder day %', v_n;
        v_n := v_n + 1;
    END LOOP;

    FOR v_i IN 1..3 LOOP
        RAISE NOTICE 'Entrance check %', v_i;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE sc6_events.book_seats(
    p_event_id   integer,
    p_student_number text,
    p_seats   integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_new_id    integer;
BEGIN
    
    IF p_seats <= 0 THEN
        RAISE EXCEPTION 'Number of seats must be positive'
            USING ERRCODE = '22023';          
    END IF;
    IF p_student_number IS NULL OR btrim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student must not be blank'
            USING ERRCODE = '22023';
    END IF;

    
    SELECT available_seats INTO v_available
    FROM sc6_events.events
    WHERE event_id = p_event_id
    FOR UPDATE;

   
    IF NOT FOUND THEN
        RAISE NOTICE 'Event % does not exist', p_event_id;
        RETURN;
    ELSIF v_available < p_seats THEN
        RAISE NOTICE 'Insufficient seats: only % available', v_available;
        RETURN;
    END IF;

    UPDATE sc6_events.events
    SET available_seats = available_seats - p_seats
    WHERE event_id = p_event_id;

    INSERT INTO sc6_events.bookings (event_id, student_number, seats, status)
    VALUES (p_event_id, p_student_number, p_seats, 'CONFIRMED')
    RETURNING booking_id INTO v_new_id;

    RAISE NOTICE 'Booking % recorded for student %', v_new_id, p_student_number;
END;
$$;


CALL sc6_events.book_seats(1, 'STU001', 40);
CALL sc6_events.book_seats(2, 'STU002', 4);
CALL sc6_events.book_seats(2, 'STU003', 20);  
SELECT event_id, event_name, available_seats
FROM sc6_events.events ORDER BY event_id;

SELECT booking_id, event_id, student_number, seats, status
FROM sc6_events.bookings ORDER BY booking_id;


CREATE OR REPLACE PROCEDURE sc6_events.cancel_booking(p_booking_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id integer;
    v_qty     integer;
BEGIN
    SELECT event_id, seats
    INTO v_item_id, v_qty
    FROM sc6_events.bookings
    WHERE booking_id = p_booking_id AND status = 'CONFIRMED'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No confirmed booking with ID %', p_booking_id;
        RETURN;
    END IF;

    UPDATE sc6_events.bookings
    SET status = 'CANCELLED'
    WHERE booking_id = p_booking_id;

    UPDATE sc6_events.events
    SET available_seats = available_seats + v_qty
    WHERE event_id = v_item_id;

    RAISE NOTICE 'Booking % cancelled; % seats released', p_booking_id, v_qty;
END;
$$;

CALL sc6_events.cancel_booking(1);  
CALL sc6_events.cancel_booking(1);  

SELECT * FROM sc6_events.events ORDER BY event_id;
SELECT booking_id, status FROM sc6_events.bookings ORDER BY booking_id;


CREATE OR REPLACE PROCEDURE sc6_events.show_tight_events(p_threshold integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR (p_limit integer) FOR
        SELECT event_name, available_seats
        FROM sc6_events.events
        WHERE available_seats <= p_limit
        ORDER BY event_id;
BEGIN
    OPEN c_low(p_threshold);
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;           
        RAISE NOTICE 'Full or nearly full: "%" (% seats left)', v_item.event_name, v_item.available_seats;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL sc6_events.show_tight_events(10);


DO $$
BEGIN
    CALL sc6_events.book_seats(3, 'STU004', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

SELECT COUNT(*) AS number_of_bookings
FROM sc6_events.bookings;       
SELECT event_id, event_name, available_seats
FROM sc6_events.events ORDER BY event_id;

SELECT booking_id, event_id, student_number, seats, status
FROM sc6_events.bookings ORDER BY booking_id;
